services:
  - type: web
    name: kahoo-game
    runtime: node
    plan: free
    buildCommand: npm install && npm run build:prod
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    autoDeploy: true
    
databases:
  - name: kahoo-postgres
    databaseName: kahoo
    user: kahoo_user
    plan: free